
server:
  port: ${PORT:8080}

mail:
  from: confirmation@gmail.com
  subject: Confirm your email

spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: sendmequiztesting@gmail.com
    password: ojlxwlmvcmfsuliu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
